# Nome da Aplicação
spring.application.name=exchange-api

# Define a porta em que a API vai rodar
# Opcional, mas boa prática para evitar conflitos
server.port=8080

# ==========================================
# CONFIGURAÇÕES DE SEGURANÇA
# ==========================================
# O Spring Security gera uma senha aleatória no console toda vez que você reinicia o projeto.
# Definir um usuário e senha padrão limpa o seu console e desativa essa geração aleatória.
spring.security.user.name=admin
spring.security.user.password=admin123

# Forçar a exibição do status de componentes internos no Spring Boot Actuator
management.endpoint.health.show-details=always

# ==========================================
# CONFIGURAÇÕES DE LOGS
# ==========================================
# Mostra logs detalhados apenas das nossas classes (DEBUG) para facilitar a caça a bugs
logging.level.com.exchange.crypto=DEBUG
# Mantém os logs do Spring Web normais (INFO)
logging.level.org.springframework.web=INFO

# ==========================================
# CONFIGURAÇÕES DE PERSISTÊNCIA E HISTÓRICO
# ==========================================
# Configuração do PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/exchange_db}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Hibernate Envers (Histórico)
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_history
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true