# Nome da Aplicação
spring.application.name=exchange-api

# Define a porta em que a API vai rodar
# Opcional, mas boa prática para evitar conflitos
server.port=8080

# ==========================================
# CONFIGURAÇÕES DE SEGURANÇA
# ==========================================
# O Spring Security gera uma senha aleatória no console toda vez que você reinicia o projeto.
# Definir um usuário e senha padrão limpa o seu console e desativa essa geração aleatória.
spring.security.user.name=admin
spring.security.user.password=admin123

# ==========================================
# CONFIGURAÇÕES DE LOGS
# ==========================================
# Mostra logs detalhados apenas das nossas classes (DEBUG) para facilitar a caça a bugs
logging.level.com.exchange.crypto=DEBUG
# Mantém os logs do Spring Web normais (INFO)
logging.level.org.springframework.web=INFO