spring.application.name=eureka-server
server.port=8761

# ### EUREKA SERVER CONFIG ###
# O servidor Eureka não deve se registrar nele mesmo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Permite que outros serviços descubram o Eureka via nome do container
eureka.instance.hostname=eureka-server