spring.application.name=config-server
server.port=8888

# Ativar pasta de configuração local, ao invés do GitHub
# Windows
# spring.cloud.config.server.native.search-locations=file:///C:/seu/caminho/config-repo
# Linux/macOS
# spring.cloud.config.server.native.search-locations=file:///home/user/config-repo
# spring.profiles.active=native
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./config-repo,file:../config-repo

# Onde ficam as configs centralizadas
# spring.cloud.config.server.git.uri=${GITHUB_REPO_URL}
# spring.cloud.config.server.git.default-label=${GIT_CONFIG_BRANCH}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka}
eureka.instance.prefer-ip-address=true